### PR TITLE
Fix location of systemd unit files.

### PR DESCRIPTION
**Pull request by mkosola**

### CODE REVIEW

**Comment by vigejolla** [comment]
I'd prefer having the Mer->Sailfish OS changes in a separate commit, but otherwise LGTM

**Comment by saukko** [comment]
Is there a reason to have .yaml here? We have been dropping use of it for a longer time already.

**Comment by vigejolla** [comment]
> Is there a reason to have .yaml here? We have been dropping use of it for a longer time already.

I'm 99,5% sure there is no reason

**Comment by mkosola** [comment]
Dropped yaml file

**Pull request merged**
